routes/web.php
    Route::POST('/male_employee_filter',['middleware'=>'check-permission:admin|hr|executive|hr-admin','uses'=>'EmployeeController@filter_male_employee']);
    Route::POST('/male_employee_search',['middleware'=>'check-permission:admin|hr|executive|hr-admin','uses'=>'EmployeeController@male_employee_search']);
    Route::get('/female_employee',['middleware'=>'check-permission:admin|hr|executive|hr-admin','uses'=>'EmployeeController@female_employee_list']);
    Route::POST('/female_employee_filter',['middleware'=>'check-permission:admin|hr|executive|hr-admin','uses'=>'EmployeeController@filter_female_employee']);
    Route::POST('/female_employee_search',['middleware'=>'check-permission:admin|hr|executive|hr-admin','uses'=>'EmployeeController@female_employee_search']);
    Route::get('/employee/bangla_information/{id}','EmployeeController@bangla_information')->name('employee.bangla_information');
    Route::POST('/employee/store_bangla_information',['middleware'=>'check-permission:admin|hr|executive|hr-admin','uses'=>'EmployeeController@store_bangla_information'])->name('employee.store_bangla_information');
    Route::post('/employee_discontinuation',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'EmployeeController@UpdateResignationDate']);
    Route::resource('/employee','EmployeeController');
    Route::get('/delete_employee_list',['middleware'=>'check-permission:admin','uses'=>'EmployeeController@delete_employee_list'])->name('employee.delete_employee_list');
    Route::get('/employee_confirm_delete/{id}',['middleware'=>'check-permission:admin','uses'=>'EmployeeController@employee_confirm_delete'])->name('employee.employee_confirm_delete');
    Route::post('/employee_confirm_delete/{id}',['middleware'=>'check-permission:admin','uses'=>'EmployeeController@employee_confirmed_delete']);
    Route::get('/user/profile',['middleware'=>'check-permission:admin|hr|executive|accountant|hr-admin','uses'=>'dashboardcontroller@user_profile'])->name('user.profile');
    Route::resource('/employee/education','EmployeeEducationInfoController',['except'=>['index','show','edit']]);
    Route::resource('/employee/training','EmployeeTrainingController',['except'=>['index','show']]);
    Route::resource('/employee/nominee','NomineeController',['except'=>['index','show']]);
    Route::resource('/employee/workexpericence','WorkingExperienceController',['except'=>['show']]);
    Route::resource('/employee/skill','SkillTestController',['except'=>['show']]);
    Route::get('/employee/workexperience/delete/{id}','WorkingExperienceController@showDelete')->name('workexperience.delete.show');
    Route::get('/employee/skill/delete/{id}','SkillTestController@showDelete')->name('skill.delete.show');
    Route::get('/employee/nominee/delete/{id}','NomineeController@showDelete')->name('nominee.delete.show');
    Route::get('/employee/training/delete/{id}','EmployeeTrainingController@showDelete')->name('training.delete.show');
    Route::resource('/employee/attachments','OtherAttachmentController',['except'=>['create','index']]);
    Route::patch('/employee/password/{id}','EmployeeController@UpdatePassword')->name('employee.password.update');
    Route::patch('/employee/photo/{id}','EmployeeController@UpdatePhoto');
    Route::patch('/employee/proxy/{id}','EmployeeController@UpdateProxy');
    Route::get('/notification/read/{id}','EmployeeController@NotificationUpdate')->name('notification.read');
    Route::get('/employee/floor/line/{id}','EmployeeController@floor_line');
    Route::get('/employeelist/continuedAbsentList',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'EmployeeController@getContinueAbsentList'])->name('employee.continued_absent_list');
    Route::get('/employeelist/continued_absent_list_data',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'EmployeeController@continued_absent_list_data'])->name('employee.continued_absent_list_data');
    Route::post('/report/continuedAbsentListNotification',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'EmployeeController@continueAbsentEmployeeNotification']);
    Route::post('/inactive_continue_absent',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'EmployeeController@inactive_continue_absent']);
    Route::get('section-autocomplete-ajax',array('as'=>'employee.section.autocomplete.ajax','uses'=>'EmployeeController@sectionAjaxData'));
    Route::POST('/store_medical_history',['middleware'=>'check-permission:admin|hr|executive|hr-admin','uses'=>'EmployeeController@store_medical_history']);
    Route::patch('/update_medical_history/{id}','EmployeeController@update_medical_history');
    Route::get('/employee_medical_history_pdf/{id}',['middleware'=>'check-permission:admin|hr|executive|hr-admin','uses'=>'EmployeeController@download_ems'])->name('employee.download_ems');
    Route::get('/AbsentEmployees/sendAutoSMS','EmployeeController@sent_auto_sms')->name('employee.continue_absent_list_autosms');
    //Employee Route End
    //Settings route start
    Route::get('/user_settings',['middleware'=>'check-permission:admin','uses'=>'SystemsettingsController@index']);
    Route::post('/user_update',['middleware'=>'check-permission:admin','uses'=>'SystemsettingsController@user_pass_update']);
    Route::resource('/settings/country','CountryController',['except'=>['show','create','edit']]);
    Route::resource('/settings/maritialstatus','MaritialStatusController',['except'=>['show','create','edit']]);
    Route::resource('/settings/department','DepartmentController',['except'=>['show','create','edit']]);
    Route::resource('/settings/designation','DesignationController',['except'=>['show','create','edit']]);
    Route::resource('/settings/unit', 'UnitController',['except'=>['create']]);
    Route::resource('/settings/line', 'LineController',['except'=>['create']]);
    Route::resource('/settings/floor','FloorController',['except'=>['create']]);
    Route::resource('/settings/overtime','OvertimeController',['except'=>['create','store','show','edit','destroy']]);
    Route::resource('/settings/overtime-hour-count','OvertimeHourCountController',['except'=>['create','store','show','edit','destroy']]);
    Route::get('/settings/unit/delete/show/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'UnitController@showDelete'])->name('unit.delete.show');
    Route::get('/settings/line/delete/show/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'LineController@showDelete'])->name('line.delete.show');
    Route::get('/settings/floor/delete/show/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'FloorController@showDelete'])->name('floor.delete.show');
    // Settings route end
    //recruitment Route Start
    Route::resource('/recruitment/vacancy','RecruitmentController',['except'=>'edit']);
    Route::get('/recruitment/application/create','RecruitmentController@vacancyApplication')->name('application.create');
    Route::post('/recruitment/application','RecruitmentController@storeVacancyApplication')->name('application.store');
    Route::get('/recruitment/application','RecruitmentController@indexVacancyApplication')->name('application.index');
    Route::get('/recruitment/status','RecruitmentController@dailyRecruitment')->name('recruitment.status');
    Route::get('/recruitment/status/{date}', 'RecruitmentController@recruitmentStatus');
    Route::get('/recruitment/application/{id}', 'RecruitmentController@detailsVacancyApplication')->name('application.details');
    Route::patch('/recruitment/application/{id}','RecruitmentController@applicationUpdate')->name('application.update');
    Route::delete('/recruitment/application/{id}','RecruitmentController@applicationDelete')->name('application.delete');
    //recruitment Route end
    //payroll Route Start
    Route::get('/report/employee/daily/salary',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalarySheet@employeeDailysalary']);
    Route::post('/report/employee/daily/salary/show',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalarySheet@employeeDailysalaryshow']);
    Route::get('/employee/grade/salary/update/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalaryController@gradeWisesalaryUpdate']);
    Route::get('/employee/salary/grade/modals/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalaryController@employeeSalaryEditmodal']);
    Route::post('/deduction_overtime',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@employee_absent_overtime']);
    Route::post('/payroll_grade_store',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@payroll_grade_store']);
    Route::get('/payroll/grade',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@payroll_grade']);
    Route::get('/payslip',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@payslip']);
    Route::get('/grade',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@payroll_grade_show']);
    Route::post('/grade_update',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@payroll_grade_update']);
    Route::get('/grade_delete/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@grade_delete']);
    Route::get('/salary_list',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalaryController@total_salary_view']);
    Route::get('/salary',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@payroll_salary']);
    Route::post('/gradeajax/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@show']);
    Route::post('/salary_store',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalaryController@store']);
    Route::get('/salary_view',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalaryController@index'])->name('salary.View');

app/Http/Controllers/LineController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class LineController extends Controller
{
    function __construct()
    {
        $this->middleware(['middleware'=>'check-permission:admin|hr|hr-admin']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $floors=DB::table('floors')->pluck('floor','id')->all();
        $lines=DB::table('tblines')
            ->leftJoin('floors','tblines.floor_id','=','floors.id')
            ->select('tblines.*','floors.floor')
            ->get();
        return view('settings.line.index',compact('lines','floors'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'line_no'=>'required',
            'floor_id'=>'required',
//            'lineDescription'=>'required',

        ]);
        DB::table('tblines')->insert([
            'line_no'=>$request->line_no,
            'lineDescription'=>$request->lineDescription,
            'floor_id'=>$request->floor_id,
            'created_at'=>Carbon::now()->toDateTimeString(),
            'updated_at'=>Carbon::now()->toDateTimeString(),
        ]);
        Session::flash('message','Line inserted');
        return redirect('settings/line');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $line=DB::table('tblines')
            ->leftJoin('floors','tblines.floor_id','=','floors.id')
            ->where(['tblines.id'=>$id])
            ->first();
        return view('settings.line.showForm',compact('line'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $floors=DB::table('floors')->pluck('floor','id')->all();
        $line=DB::table('tblines')->where(['id'=>$id])->first();
        return view('settings.line.editForm',compact('line','floors'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'line_no'=>'required',
            'floor_id'=>'required',
        ]);
        DB::table('tblines')->where(['id'=>$id])->update([
            'line_no'=>$request->line_no,
            'floor_id'=>$request->floor_id,
            'lineDescription'=>$request->lineDescription,
            'updated_at'=>Carbon::now()->toDateTimeString(),
        ]);
        Session::flash('edit','Line Information Updated');
        return redirect('settings/line');
    }

    public function showDelete($id){
        $line=DB::table('tblines')->where(['id'=>$id])->first();
        return view('settings.line.deleteForm',compact('line'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('tblines')->where(['id'=>$id])->delete();
        Session::flash('delete','Line information deleted');
        return redirect('settings/line');
    }
}

app/Http/Controllers/SettingsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Redirect;
use Session;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;

class SettingsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $settings=DB::table('settings')->latest()->get();
        return view('settings.system_settings.index',compact('settings'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function settings_store(Request $request)
    {
        $file=$request->file('logo_name');
        $current_time = Carbon::now()->toDateTimeString();
        $csv_file=time()."_".$request->file('logo_name')->getClientOriginalName();
        $file->move(public_path('\logo'),time()."_".$file->getClientOriginalName());
        $store_logo=DB::table('settings')->insert([
            'logo' =>$csv_file,
            'copyright' =>$request->copyright,
            'created_at' =>$current_time,
            'updated_at' =>$current_time,
        ]);
        if($store_logo){
            Session::flash('message', 'Store Successful!');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function settings_update(Request $request)
    {
      $id=$request->settings_hidden_id;
        $file=$request->file('logo_name');
        $current_time = Carbon::now()->toDateTimeString();
        $csv_file=time()."_".$request->file('logo_name')->getClientOriginalName();
        $file->move(base_path('\file'),time()."_".$file->getClientOriginalName());
        $update_settingss=DB::table('settings')->WHERE('id',$id)->update([
            'logo' =>$csv_file,
            'copyright' =>$request->copyright,
            'created_at' =>$current_time,
            'updated_at' =>$current_time,
        ]);
        if($update_settingss){
            Session::flash('message', 'Update Successful!');
            return redirect()->back();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function settings_delete($id)
    {
        $data=DB::table('settings')->WHERE('id',$id)->delete();
        if($data){
            Session::flash('message', 'Delete Successful!');
            return redirect()->back();
        }
    }

    public function style()
    {
        return view('settings.system_settings.style');
    }

    public function changeStyle(Request $request)
    {
        $user=Auth::user();

        $str=DB::table('users')->where(['id'=>$user->id])->update([
            'theme_style'=>$request->themeStyle,
        ]);

        if($str>0)
        {
            Session::flash('message','Theme Style has been changed. Please refresh(press ctrl+f5 to refresh ) your browser if is it not rendering currectly. ');
        }else{
            Session::flash('failedMessage','Failed to change theme style. Try again later...');
        }
        // return $str;
        return redirect()->back();
    }
}

resources/views/settings/line/deleteForm.blade.php
{!! Form::open(['method'=>'DELETE','action'=>['LineController@destroy',$line->id]]) !!}

<div class="container">
    <p>You sure you want to delete <strong>{{ $line->line_no }}</strong> ??</p>
</div>


<div class="text-center  m-t-20">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" id="update-unit" class="btn btn-embossed btn-primary">Confirm Delete</button>
</div>

{!! Form::close() !!}

resources/views/settings/line/editForm.blade.php
{!! Form::open(['method'=>'PATCH','action'=>['LineController@update',$line->id],'files'=>true]) !!}

<div class="row">
    <div class="col-sm-12">
        <div class="required form-group">
            {!! Form::label('line','Line Number',['class'=>'control-label']) !!}
            <div class="append-icon">
                <input type="text" name="line_no" value="{{$line->line_no}}" class="form-control" placeholder="Enter Name..." required>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="required form-group">
            <div class="form-group">
                {!! Form::label('floor_id','Floor:') !!}
                {!! Form::select('floor_id',[''=>'Select Floor']+$floors,$line->floor_id,['class'=>'form-control','required'=>'', 'data-search'=>'true']) !!}

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label class="control-label">Description</label>
            <div class="append-icon">
                <textarea name="lineDescription" class="form-control" placeholder="Enter Line Description..." rows="4"> {{$line->lineDescription}}</textarea>
                <i class="icon-lock"></i>
            </div>
        </div>
    </div>

</div>



<div class="text-center  m-t-20">
    <button type="submit" id="update-unit" class="btn btn-embossed btn-primary">Update Info</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

{!! Form::close() !!}

resources/views/settings/line/index.blade.php
@extends('layouts.master')
@section('title', 'Line List')
@section('content')
    <div class="page-content">
        @if(Session::has('message'))
            <p id="alert_message" class="alert alert-success">{{ Session::get('message') }}</p>
        @endif
        @if(Session::has('delete'))

            <p id="alert_message" class="alert alert-danger">{{Session::get('delete')}}</p>

        @endif
        @if(Session::has('edit'))

            <p id="alert_message" class="alert alert-info">{{Session::get('edit')}}</p>

        @endif
        <div class="row">
            <div class="col-lg-12 portlets">
                <div class="panel">
                    <div class="panel-header">
                        <div class="row">
                            <div class="col-md-4">
                                <h3><i class="fa fa-table"></i> <strong>Line </strong> List</h3>
                            </div>
                            <div class="col-md-8" style="margin-top:8px; text-align: right;">
                               <a data-toggle="modal" data-target="#linecreate" class="btn btn-blue btn-sm"><i class="fa fa-plus"></i> Add New</a>
                            </div>
                          </div>

                    </div>
                    <div class="panel-content pagination2 table-responsive">
                        <table class="table table-hover table-bordered table-dynamic">
                            <thead>
                            <tr>
                                <th width="5%">id</th>
                                <th>Line Number</th>
                                <th>Floor</th>
                                <th>Description</th>
                                <th width="20%" style="text-align: center;">Action</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($lines as $line)
                                <tr>
                                    <td>{{$line->id}}</td>
                                    <td>{{$line->line_no}}</td>
                                    <td>{{$line->floor}}</td>
                                    <td>{{$line->lineDescription}}</td>
                                    <td style="text-align: center;">
                                        <a href="{{route('line.show',$line->id)}}" title="View" class="btn btn-primary btn-sm view-line"><i class="fa fa-eye"></i></a>

                                        @if(checkPermission(['admin']))
                                        <a href="{{route('line.edit',$line->id)}}" title="Edit" class="btn btn-default btn-sm edit-line"><i class="fa fa-edit"></i></a>
                                        <a href="{{route('line.delete.show',$line->id)}}" title="Delete Data" class="btn btn-danger btn-sm delete-line"><i class="fa fa-trash"></i></a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <!-- Add New Modal -->
    <div class="modal fade" id="linecreate" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><strong>Add New Line</strong>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </h5>

                </div>
                <div id="create-new" class="modal-body">
                    {!! Form::open(['method'=>'POST', 'action'=>'LineController@store']) !!}
                    <div class="form-group">
                        {!! Form::label('line_no','Line Number:') !!}
                        {!! Form::text('line_no',null,['class'=>'form-control','required'=>'', 'placeholder'=>'Enter Line Number']) !!}

                    </div>
                    <div class="form-group">
                        {!! Form::label('floor_id','Floor:') !!}
                        {!! Form::select('floor_id',[''=>'Select Floor']+$floors,null,['class'=>'form-control','required'=>'', 'data-search'=>'true']) !!}

                    </div>

                    <div class="form-group">
                        {!! Form::label('lineDescription','Description:') !!}
                        {!! Form::textarea('lineDescription',null,['class'=>'form-control', 'placeholder'=>'Enter Description']) !!}

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="Submit" id="addUnit" class="btn btn-primary">Save Information</button>
                    </div>
                    {!! Form::close() !!}
                </div>

            </div>
        </div>
    </div>

    <div class="modal fade" id="edit-line-modal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icons-office-52"></i></button>
                    <h4 class="modal-title"><strong>Edit Line</strong> Details</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="edit-form col-md-12 col-sm-12 col-xs-12">


                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="delete-line-modal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icons-office-52"></i></button>
                    <h4 class="modal-title"><strong>Confirm Delete</strong></h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="delete-form col-md-12 col-sm-12 col-xs-12">


                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="view-line-modal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icons-office-52"></i></button>
                    <h4 class="modal-title"><strong>Line Details</strong></h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="view-form col-md-12 col-sm-12 col-xs-12">


                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>

    <script>

        $('.document').ready(function () {
            $(document.body).on('click','.view-line',function (event) {
                event.preventDefault();
                var url=$(this).attr('href'),
                    method='GET';

                $.ajax({
                    url:url,
                    method:method,
                    dataType:'html',
                    success:function (response) {
                        $('.view-form').html(response);


                    },
                    error:function (xhr) {

                    }
                })
                $('#view-line-modal').modal('show');

            });
            $(document.body).on('click','.edit-line',function (event) {
//                alert('k');
                event.preventDefault();
                var url=$(this).attr('href');
//                alert(url);
                $.ajax({
                    url:url,
                    method:'GET',
                    dataType:'html',
                    success:function (response) {
                        $('.edit-form').html(response);

                    },
                    error:function (xhr) {
                        console.log(xhr);

                    }
                });


                $('#edit-line-modal').modal('show');

            });

            $(document.body).on('click','.delete-line',function (event) {
                event.preventDefault();
                var url=$(this).attr('href');
//                alert(url);
                $.ajax({
                    url:url,
                    method:'get',
                    dataType:'html',
                    success:function (response) {
                        $('.delete-form').html(response);

                    },
                    error:function (xhr) {

                    }
                });
                $('#delete-line-modal').modal('show');


            });

        });


        setTimeout(function() {
            $('#alert_message').fadeOut('fast');
        }, 5000);


    </script>


    @include('include.copyright')
@endsection

resources/views/settings/line/showForm.blade.php
<div class="row">
    <div class="col-sm-12">
        <div class="required form-group">
            {!! Form::label('name','Name',['class'=>'control-label']) !!}
            <div class="append-icon">
                <input type="text" name="name" value="{{$line->line_no}}" class="form-control" placeholder="Enter line number..." required disabled>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="required form-group">
            <div class="form-group">
                {!! Form::label('floor_id','Floor:') !!}
                {!! Form::text('floor_id',$line->floor,['class'=>'form-control','required'=>'', 'disabled'=>'','data-search'=>'true']) !!}

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label class="control-label">Description</label>
            <div class="append-icon">
                <textarea name="address" class="form-control" placeholder="Enter description..." rows="4" required disabled> {{$line->lineDescription}}</textarea>
                <i class="icon-lock"></i>
            </div>
        </div>
    </div>

</div>


<div class="text-center  m-t-20">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>