routes/web.php
    Route::get('/employee_confirm_delete/{id}',['middleware'=>'check-permission:admin','uses'=>'EmployeeController@employee_confirm_delete'])->name('employee.employee_confirm_delete');
    Route::post('/employee_confirm_delete/{id}',['middleware'=>'check-permission:admin','uses'=>'EmployeeController@employee_confirmed_delete']);
    Route::get('/user/profile',['middleware'=>'check-permission:admin|hr|executive|accountant|hr-admin','uses'=>'dashboardcontroller@user_profile'])->name('user.profile');
    Route::resource('/employee/education','EmployeeEducationInfoController',['except'=>['index','show','edit']]);
    Route::resource('/employee/training','EmployeeTrainingController',['except'=>['index','show']]);
    Route::resource('/employee/nominee','NomineeController',['except'=>['index','show']]);
    Route::resource('/employee/workexpericence','WorkingExperienceController',['except'=>['show']]);
    Route::resource('/employee/skill','SkillTestController',['except'=>['show']]);
    Route::get('/employee/workexperience/delete/{id}','WorkingExperienceController@showDelete')->name('workexperience.delete.show');
    Route::get('/employee/skill/delete/{id}','SkillTestController@showDelete')->name('skill.delete.show');
    Route::get('/employee/nominee/delete/{id}','NomineeController@showDelete')->name('nominee.delete.show');
    Route::get('/employee/training/delete/{id}','EmployeeTrainingController@showDelete')->name('training.delete.show');
    Route::resource('/employee/attachments','OtherAttachmentController',['except'=>['create','index']]);
    Route::patch('/employee/password/{id}','EmployeeController@UpdatePassword')->name('employee.password.update');
    Route::patch('/employee/photo/{id}','EmployeeController@UpdatePhoto');
    Route::patch('/employee/proxy/{id}','EmployeeController@UpdateProxy');
    Route::get('/notification/read/{id}','EmployeeController@NotificationUpdate')->name('notification.read');
    Route::get('/employee/floor/line/{id}','EmployeeController@floor_line');
    Route::get('/employeelist/continuedAbsentList',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'EmployeeController@getContinueAbsentList'])->name('employee.continued_absent_list');
    Route::get('/employeelist/continued_absent_list_data',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'EmployeeController@continued_absent_list_data'])->name('employee.continued_absent_list_data');
    Route::post('/report/continuedAbsentListNotification',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'EmployeeController@continueAbsentEmployeeNotification']);
    Route::post('/inactive_continue_absent',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'EmployeeController@inactive_continue_absent']);
    Route::get('section-autocomplete-ajax',array('as'=>'employee.section.autocomplete.ajax','uses'=>'EmployeeController@sectionAjaxData'));
    Route::POST('/store_medical_history',['middleware'=>'check-permission:admin|hr|executive|hr-admin','uses'=>'EmployeeController@store_medical_history']);
    Route::patch('/update_medical_history/{id}','EmployeeController@update_medical_history');
    Route::get('/employee_medical_history_pdf/{id}',['middleware'=>'check-permission:admin|hr|executive|hr-admin','uses'=>'EmployeeController@download_ems'])->name('employee.download_ems');
    Route::get('/AbsentEmployees/sendAutoSMS','EmployeeController@sent_auto_sms')->name('employee.continue_absent_list_autosms');
    //Employee Route End
    //Settings route start
    Route::get('/user_settings',['middleware'=>'check-permission:admin','uses'=>'SystemsettingsController@index']);
    Route::post('/user_update',['middleware'=>'check-permission:admin','uses'=>'SystemsettingsController@user_pass_update']);
    Route::resource('/settings/country','CountryController',['except'=>['show','create','edit']]);
    Route::resource('/settings/maritialstatus','MaritialStatusController',['except'=>['show','create','edit']]);
    Route::resource('/settings/department','DepartmentController',['except'=>['show','create','edit']]);
    Route::resource('/settings/designation','DesignationController',['except'=>['show','create','edit']]);
    Route::resource('/settings/unit', 'UnitController',['except'=>['create']]);
    Route::resource('/settings/line', 'LineController',['except'=>['create']]);
    Route::resource('/settings/floor','FloorController',['except'=>['create']]);
    Route::resource('/settings/overtime','OvertimeController',['except'=>['create','store','show','edit','destroy']]);
    Route::resource('/settings/overtime-hour-count','OvertimeHourCountController',['except'=>['create','store','show','edit','destroy']]);
    Route::get('/settings/unit/delete/show/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'UnitController@showDelete'])->name('unit.delete.show');
    Route::get('/settings/line/delete/show/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'LineController@showDelete'])->name('line.delete.show');
    Route::get('/settings/floor/delete/show/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'FloorController@showDelete'])->name('floor.delete.show');
    // Settings route end
    //recruitment Route Start
    Route::resource('/recruitment/vacancy','RecruitmentController',['except'=>'edit']);
    Route::get('/recruitment/application/create','RecruitmentController@vacancyApplication')->name('application.create');
    Route::post('/recruitment/application','RecruitmentController@storeVacancyApplication')->name('application.store');
    Route::get('/recruitment/application','RecruitmentController@indexVacancyApplication')->name('application.index');
    Route::get('/recruitment/status','RecruitmentController@dailyRecruitment')->name('recruitment.status');
    Route::get('/recruitment/status/{date}', 'RecruitmentController@recruitmentStatus');
    Route::get('/recruitment/application/{id}', 'RecruitmentController@detailsVacancyApplication')->name('application.details');
    Route::patch('/recruitment/application/{id}','RecruitmentController@applicationUpdate')->name('application.update');
    Route::delete('/recruitment/application/{id}','RecruitmentController@applicationDelete')->name('application.delete');
    //recruitment Route end
    //payroll Route Start
    Route::get('/report/employee/daily/salary',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalarySheet@employeeDailysalary']);
    Route::post('/report/employee/daily/salary/show',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalarySheet@employeeDailysalaryshow']);
    Route::get('/employee/grade/salary/update/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalaryController@gradeWisesalaryUpdate']);
    Route::get('/employee/salary/grade/modals/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalaryController@employeeSalaryEditmodal']);
    Route::post('/deduction_overtime',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@employee_absent_overtime']);
    Route::post('/payroll_grade_store',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@payroll_grade_store']);
    Route::get('/payroll/grade',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@payroll_grade']);
    Route::get('/payslip',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@payslip']);
    Route::get('/grade',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@payroll_grade_show']);
    Route::post('/grade_update',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@payroll_grade_update']);
    Route::get('/grade_delete/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@grade_delete']);
    Route::get('/salary_list',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalaryController@total_salary_view']);
    Route::get('/salary',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@payroll_salary']);
    Route::post('/gradeajax/{id}',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@show']);
    Route::post('/salary_store',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalaryController@store']);
    Route::get('/salary_view',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalaryController@index'])->name('salary.View');
    Route::post('/salary_up',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalaryController@update']);
    Route::post('/employee_salary_update',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'SalaryController@update'])->name('salary.employee_salary_update');
    Route::get('/payroll/salary',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@payroll_salary']);
    Route::post('/employee/bonus/store',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@bonus_emloyee']);
    Route::post('/overtime_employee',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@employee_overtime']);
    Route::post('/overtime_employee_store',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@overtime_amount_hour_store']);
    Route::post('/attendancebonus',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@AttendanceBonus']);
    Route::post('/festivalbonus',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@empFestivalbonus']);
    Route::post('/leave_employee',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@leave_employee']);
    Route::post('/pres_employee',['middleware'=>'check-permission:admin|hr|hr-admin','uses'=>'PayrollController@employee_present_days_count']);

app/Http/Controllers/SettingsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Redirect;
use Session;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;

class SettingsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $settings=DB::table('settings')->latest()->get();
        return view('settings.system_settings.index',compact('settings'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function settings_store(Request $request)
    {
        $file=$request->file('logo_name');
        $current_time = Carbon::now()->toDateTimeString();
        $csv_file=time()."_".$request->file('logo_name')->getClientOriginalName();
        $file->move(public_path('\logo'),time()."_".$file->getClientOriginalName());
        $store_logo=DB::table('settings')->insert([
            'logo' =>$csv_file,
            'copyright' =>$request->copyright,
            'created_at' =>$current_time,
            'updated_at' =>$current_time,
        ]);
        if($store_logo){
            Session::flash('message', 'Store Successful!');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function settings_update(Request $request)
    {
      $id=$request->settings_hidden_id;
        $file=$request->file('logo_name');
        $current_time = Carbon::now()->toDateTimeString();
        $csv_file=time()."_".$request->file('logo_name')->getClientOriginalName();
        $file->move(base_path('\file'),time()."_".$file->getClientOriginalName());
        $update_settingss=DB::table('settings')->WHERE('id',$id)->update([
            'logo' =>$csv_file,
            'copyright' =>$request->copyright,
            'created_at' =>$current_time,
            'updated_at' =>$current_time,
        ]);
        if($update_settingss){
            Session::flash('message', 'Update Successful!');
            return redirect()->back();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function settings_delete($id)
    {
        $data=DB::table('settings')->WHERE('id',$id)->delete();
        if($data){
            Session::flash('message', 'Delete Successful!');
            return redirect()->back();
        }
    }

    public function style()
    {
        return view('settings.system_settings.style');
    }

    public function changeStyle(Request $request)
    {
        $user=Auth::user();

        $str=DB::table('users')->where(['id'=>$user->id])->update([
            'theme_style'=>$request->themeStyle,
        ]);

        if($str>0)
        {
            Session::flash('message','Theme Style has been changed. Please refresh(press ctrl+f5 to refresh ) your browser if is it not rendering currectly. ');
        }else{
            Session::flash('failedMessage','Failed to change theme style. Try again later...');
        }
        // return $str;
        return redirect()->back();
    }
}

app/Http/Controllers/UnitController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class UnitController extends Controller
{

    function __construct()
    {
        $this->middleware([
            'middleware'=>'check-permission:admin|hr|hr-admin'
        ]);
    }

    public function index()
    {
        $units=DB::table('units')->orderBy('id','asc')->get();
//        return $units;

        return view('settings.unit.index',compact('units'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required',
            'phone_no'=>'required',
            'email'=>'required',
            'address'=>'required',
        ]);
        $id=DB::table('units')->insert([
            'name'=>$request->name,
            'phone_no'=>$request->phone_no,
            'email'=>$request->email,
            'address'=>$request->address,
        ]);
        Session::flash('message','Unit Inserted Successfully');
        return redirect('settings/unit');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $unit=DB::table('units')->where(['id'=>$id])->first();
        return view('settings.unit.show',compact('unit'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $unit=DB::table('units')->where(['id'=>$id])->first();
        return view('settings.unit.editForm',compact('unit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
//        return $request->all();

        $this->validate($request,[
            'name'=>'required',
            'phone_no'=>'required',
            'email'=>'required',
            'address'=>'required',
        ]);


        DB::table('units')->where(['id'=>$id])->update([
            'name'=>$request->name,
            'phone_no'=>$request->phone_no,
            'email'=>$request->email,
            'address'=>$request->address,
        ]);

        Session::flash('edit','Unit information updated');
        return redirect('settings/unit');

    }

    public function showDelete($id){
        $unit=DB::table('units')->where(['id'=>$id])->first();
        return view('settings.unit.deleteForm',compact('unit'));


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $check=DB::table('employees')->where('unit_id','=',$id)->get();
        if(count($check)){
            Session::flash('failedMessage',"Can't delete. There are already some employees in this unit." );
        }
        else {
            DB::table('units')->where('id','=',$id)->delete();
            Session::flash('message', 'Unit information has been successfully deleted. ');
        }
        return redirect()->back();

    }
}

resources/views/settings/unit/deleteForm.blade.php
{!! Form::open(['method'=>'DELETE','action'=>['UnitController@destroy',$unit->id]]) !!}

<div class="container">
    <p>You sure you want to delete <strong>{{ $unit->name }}</strong> unit ??</p>
</div>


<div class="text-center  m-t-20">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" id="update-unit" class="btn btn-embossed btn-primary">Confirm Delete</button>
</div>

{!! Form::close() !!}

resources/views/settings/unit/editForm.blade.php
{!! Form::open(['method'=>'PATCH','action'=>['UnitController@update',$unit->id],'files'=>true]) !!}

<div class="row">
    <div class="col-sm-12">
        <div class="required form-group">
            {!! Form::label('name','Name',['class'=>'control-label']) !!}
            <div class="append-icon">
                <input type="text" name="name" value="{{$unit->name}}" class="form-control" placeholder="Enter Name..." required>
            </div>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="form-group">
            {!! Form::label('phone_no','Phone Number',['class'=>'control-label']) !!}
            <div class="append-icon">
                <input type="text" name="phone_no" value="{{ $unit->phone_no }}" class="form-control" placeholder="Enter Phone Number" required>
            </div>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group">
            {!! Form::label('email','Email Address',['class'=>'control-label']) !!}
            <div class="append-icon">
                <input type="text" name="email" value="{{$unit->email}}" class="form-control" placeholder="Enter Email Address" required>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label class="control-label">Address</label>
            <div class="append-icon">
                <textarea name="address" class="form-control" placeholder="Enter address details..." rows="4" required> {{$unit->address}}</textarea>
                <i class="icon-lock"></i>
            </div>
        </div>
    </div>

</div>



<div class="text-center  m-t-20">
    <button type="submit" id="update-unit" class="btn btn-embossed btn-primary">Update Info</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

{!! Form::close() !!}

resources/views/settings/unit/index.blade.php
@extends('layouts.master')
@section('title', 'Unit List')
@section('content')
    <div class="page-content">
        @if(Session::has('message'))
            <p id="alert_message" class="alert alert-success">{{ Session::get('message') }}</p>
        @endif
        @if(Session::has('delete'))

            <p id="alert_message" class="alert alert-danger">{{Session::get('delete')}}</p>

        @endif
        @if(Session::has('edit'))

            <p id="alert_message" class="alert alert-info">{{Session::get('edit')}}</p>

        @endif
        
        <style type="text/css">
            .modal-title{
                color:#222;
            }
        </style>
        <div class="row">
            <div class="col-lg-12 portlets">
                <div class="panel">
                    <div class="panel-header">
                        <div class="row">
                            <div class="col-lg-6">
                               <h3><i class="fa fa-table"></i> <strong>Unit </strong> List</h3>
                            </div>
                            <div class="col-lg-6" style="text-align: right;">
                                 <a data-toggle="modal" data-target="#usercreate" class="btn btn-blue"><i class="fa fa-plus"></i>Add New</a>
                            </div>
                        </div>
                    </div>
                    <div class="panel-content pagination2 table-responsive">
                        <table class="table table-hover table-bordered table-dynamic">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Phone Number</th>
                                <th>Email</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>

                                @foreach($units as $unit)
                                    <tr>
                                        <td>{{$unit->name}}</td>
                                        <td>{{$unit->phone_no}}</td>
                                        <td>{{$unit->email}}</td>
                                        <td>
                                            <a href="{{route('unit.show',$unit->id)}}" title="View" class="btn btn-primary btn-sm view-unit"><i class="fa fa-eye"></i></a>
                                            @if(checkPermission(['admin']))
                                            <a href="{{route('unit.edit',$unit->id)}}" title="Edit" class="btn btn-success btn-sm edit-unit"><i class="fa fa-edit"></i></a>
                                            <a href="{{route('unit.delete.show',$unit->id)}}" title="Delete Data" class="btn btn-danger btn-sm delete-unit"><i class="fa fa-trash"></i></a>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <!-- Add New Modal -->
    <div class="modal fade" id="usercreate" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><strong>Add New Unit</strong>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </h5>

                </div>
                <div id="create-new" class="modal-body">
                    {!! Form::open(['method'=>'POST', 'action'=>'UnitController@store']) !!}
                    <div class="form-group">
                        {!! Form::label('name','Unit Name:') !!}
                        {!! Form::text('name',null,['class'=>'form-control','required'=>'', 'placeholder'=>'Enter Unit Name']) !!}

                    </div>

                    <div class="form-group">
                        {!! Form::label('phone_no','Phone Number:') !!}
                        {!! Form::text('phone_no',null,['class'=>'form-control','required'=>'', 'placeholder'=>'Enter Phone Number']) !!}

                    </div>
                    <div class="form-group">
                        {!! Form::label('email','Email Address:') !!}
                        {!! Form::email('email',null,['class'=>'form-control','required'=>'', 'placeholder'=>'Enter Email Address']) !!}

                    </div>
                    <div class="form-group">
                        {!! Form::label('address','Full Address:') !!}
                        {!! Form::textarea('address', null,['class'=>'form-control','required'=>'', 'placeholder'=>'Enter Address']) !!}

                    </div>
                    <div class="modal-footer">
                        <button type="Submit" id="addUnit" class="btn btn-primary"> <i class="fa fa-save"></i> &nbsp;Save Information </button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                    {!! Form::close() !!}
                </div>

            </div>
        </div>
    </div>







    <div class="modal fade" id="edit-unit-modal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icons-office-52"></i></button>
                    <h4 class="modal-title"><strong>Edit Unit</strong> Details</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="edit-form col-md-12 col-sm-12 col-xs-12">


                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="delete-unit-modal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icons-office-52"></i></button>
                    <h4 class="modal-title"><strong>Confirm Delete</strong></h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="delete-form col-md-12 col-sm-12 col-xs-12">


                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="view-unit-modal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icons-office-52"></i></button>
                    <h4 class="modal-title"><strong>Unit Details</strong></h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="view-form col-md-12 col-sm-12 col-xs-12">


                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>

    <script>

        $('.document').ready(function () {
            $(document.body).on('click','.view-unit',function (event) {
                event.preventDefault();
                var url=$(this).attr('href'),
                    method='GET';

                $.ajax({
                    url:url,
                    method:method,
                    dataType:'html',
                    success:function (response) {
                        $('.view-form').html(response);


                    },
                    error:function (xhr) {

                    }
                })
                $('#view-unit-modal').modal('show');

            });
            $(document.body).on('click','.edit-unit',function (event) {
                event.preventDefault();
                var url=$(this).attr('href');
                $.ajax({
                    url:url,
                    method:'GET',
                    dataType:'html',
                    success:function (response) {
                        $('.edit-form').html(response);

                    },
                    error:function (xhr) {
                        console.log(xhr);

                    }
                });


                $('#edit-unit-modal').modal('show');

            });

            $(document.body).on('click','.delete-unit',function (event) {
                event.preventDefault();
                var url=$(this).attr('href');
//                alert(url);
                $.ajax({
                    url:url,
                    method:'get',
                    dataType:'html',
                    success:function (response) {
                        $('.delete-form').html(response);

                    },
                    error:function (xhr) {

                    }
                });
                $('#delete-unit-modal').modal('show');


            });

        });


        setTimeout(function() {
            $('#alert_message').fadeOut('fast');
        }, 5000);


    </script>


    @include('include.copyright')
@endsection

resources/views/settings/unit/show.blade.php
<div class="row">
    <div class="col-sm-12">
        <div class="required form-group">
            {!! Form::label('name','Name',['class'=>'control-label']) !!}
            <div class="append-icon">
                <input type="text" name="name" value="{{$unit->name}}" class="form-control" placeholder="Enter Name..." required disabled>
            </div>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="form-group">
            {!! Form::label('phone_no','Phone Number',['class'=>'control-label']) !!}
            <div class="append-icon">
                <input type="text" name="phone_no" value="{{ $unit->phone_no }}" class="form-control" placeholder="Enter Phone Number" required disabled>
            </div>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group">
            {!! Form::label('email','Email Address',['class'=>'control-label']) !!}
            <div class="append-icon">
                <input type="text" name="email" value="{{$unit->email}}" class="form-control" placeholder="Enter Email Address" required disabled>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label class="control-label">Address</label>
            <div class="append-icon">
                <textarea name="address" class="form-control" placeholder="Enter the interview details..." rows="4" required disabled> {{$unit->address}}</textarea>
                <i class="icon-lock"></i>
            </div>
        </div>
    </div>

</div>


<div class="text-center  m-t-20">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>